version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    ports:
      - "9000:9000"
  web:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
